### PR TITLE
Create top-userlisticons.js

### PR DESCRIPTION
**Pull request by KevinNeon**

### CODE REVIEW

**Comment by AllianceSky-PS** [comment]
@KevinNeon can you explain why it's better than current icons.js plugin?

**Comment by KevinNeon** [comment]
this is not icons.js this is userlist icons it can give icon on the top of userlist

**Comment by AllianceSky-PS** [comment]
@KevinNeon so is it room icon or something like that?. Can explain how it works and what it does.

**Comment by KevinNeon** [comment]
Well check this screenshot https://image.prntscr.com/image/5-eKWlVVRiy_k1LhrR4QDA.jpeg

**Comment by AllianceSky-PS** [comment]
Have you tested it?

**Comment by KevinNeon** [comment]
yeah add it -_-

**Pull request merged**
